# Generated by Django 4.1.3 on 2022-12-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="in_active",
            field=models.BooleanField(default=True),
        ),
    ]
