# Generated by Django 4.1.3 on 2022-12-01 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_in_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="in_active",
            new_name="is_active",
        ),
    ]
